"""Summarise recorded conditions into results/datacard.md.

uv run python -m llm_gateway.research.datacard [--recordings data/recordings] [--out results/datacard.md]
"""

import argparse
import json
from pathlib import Path

import pandas as pd


def load_condition(path: Path) -> tuple[pd.DataFrame, dict]:
    signals = pd.read_parquet(path / "signals")
    client = pd.read_parquet(path / "client.parquet")[["request_id", "item_id", "correct"]]
    meta = json.loads((path / "meta.json").read_text())
    return signals.merge(client, on="request_id", how="left"), meta


def load_all(root: Path) -> pd.DataFrame:
    frames = []
    for path in sorted(p for p in root.iterdir() if (p / "DONE").exists()):
        df, meta = load_condition(path)
        frames.append(df.assign(condition=meta["condition"]))
    return pd.concat(frames, ignore_index=True)


def summary(df: pd.DataFrame) -> pd.DataFrame:
    def per_condition(g: pd.DataFrame) -> pd.Series:
        tools = g[g.tools_offered]
        math = g[g.tenant == "math"]
        return pd.Series({
            "provider": g.provider.iloc[0],
            "requests": len(g),
            "http_ok_%": 100 * (g.status_code == 200).mean(),
            "out_tokens_mean": g.completion_tokens.mean(),
            "finish_length_%": 100 * (g.finish_reason == "length").mean(),
            "empty_%": 100 * g["empty"].mean(),
            "refusal_%": 100 * g["refusal"].mean(),
            "repetition_mean": g["repetition"].mean(),
            "tool_called_%": 100 * (tools.tool_calls > 0).mean() if len(tools) else float("nan"),
            "tool_valid_%": 100 * tools.tool_call_valid.dropna().astype(float).mean() if len(tools) else float("nan"),
            "gsm8k_acc_%": 100 * math.correct.dropna().astype(float).mean() if len(math) else float("nan"),
            "ttft_p50_s": g.ttft_s.median(),
            "tok_per_s_p50": g.tokens_per_s.median(),
            "minutes": (g.ts.max() - g.ts.min()) / 60,
        })  # fmt: skip

    return df.groupby("condition").apply(per_condition, include_groups=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--recordings", type=Path, default=Path("data/recordings"))
    parser.add_argument("--out", type=Path, default=Path("results/datacard.md"))
    args = parser.parse_args()
    df = load_all(args.recordings)
    table = summary(df).round(2)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    per_tenant = df.groupby(["condition", "tenant"]).size().unstack(fill_value=0)
    args.out.write_text(
        "# Data card: recorded conditions\n\n"
        "Generated by `python -m llm_gateway.research.datacard`. Raw recordings live in `data/recordings/` "
        "(gitignored): one gateway signal log (Parquet) plus a client-side ground-truth sidecar per condition. "
        "Signals contain no prompt or response text.\n\n"
        f"Total requests: **{len(df):,}** across **{df.condition.nunique()}** conditions.\n\n"
        "## Per condition\n\n"
        + table.to_markdown()
        + "\n\n## Requests per tenant\n\n"
        + per_tenant.to_markdown()
        + "\n"
    )
    print(args.out.read_text())


if __name__ == "__main__":
    main()
